# https://github.com/zeno-ml/zeno-hub/blob/main/docker-compose.yml
version: "3"
services:
    frontend:
        container_name: venome-frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile.prod
        ports:
            - "5173:5173"
        command: yarn preview -- --host 0.0.0.0 --port 5173
    backend:
        container_name: venome-backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        depends_on:
            - postgres
        environment:
            PUBLIC_FRONTEND_URL: http://localhost:5173
            BACKEND_HOST: localhost
            BACKEND_PORT: 8000
            DB_HOST: postgres
            DB_PORT: 5432
            DB_NAME: venome
            DB_USER: myuser
            DB_PASSWORD: mypassword
        volumes:
            - backend_data:/app/src/data # so the inserted files persist
        command: poetry run uvicorn --factory src.server:export_app_for_docker --host 0.0.0.0 --timeout-keep-alive 75

    postgres:
        container_name: venome-postgres
        image: postgres:latest
        environment:
            POSTGRES_DB: venome
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
        volumes:
            - postgres_data:/var/lib/postgresql/data # so the inserted data persists even when docker is turned off

        ports:
            # Use a different port to avoid clashes with local postgres
            - "3000:5432"

volumes:
    postgres_data:
    backend_data:
