[tool.poetry]
name = "src"
version = "0.0.1"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"


[tool.poetry.dependencies]
python = ">=3.9,<3.13"
numpy = "^1.26.1"
uvicorn = "^0.23.2"
fastapi = "^0.104.0"
psycopg = "^3.1.12"
psycopg-pool = "^3.1.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
dev = "src.server:poetry_run_dev"
