# modified from https://github.com/zeno-ml/zeno-hub/blob/main/.github/workflows/ci.yml
name: ci

on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:

jobs:
    backend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: chartboost/ruff-action@v1
              with:
                  src: "backend/src/"
            - uses: chartboost/ruff-action@v1
              with:
                  args: "format --check"
                  src: "backend/src/"

    test:
        runs-on: ubuntu-latest

        services:
             postgres:
                 image: postgres:13
                 env:
                     POSTGRES_USER: myuser
                     POSTGRES_PASSWORD: mypassword
                     POSTGRES_DB: venome
                 ports:
                     - 5432:5432
                 options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
            - uses: actions/setup-python@v4
              with:
                  python-version: 3.11

            - name: Install Poetry
              uses: snok/install-poetry@v1.3.4
              with:
                  virtualenvs-in-project: true
                  virtualenvs-path: ~/.venv

            - name: Cache Poetry virtualenv
              uses: actions/cache@v3.4.3
              id: cache-poetry
              with:
                  path: ~/.venv
                  key: poetry-${{ hashFiles('**/poetry.lock') }}
                  restore-keys: |
                      poetry-${{ hashFiles('**/poetry.lock') }}
            - name: Install Poetry Dependencies
              if: steps.cache-poetry.outputs.cache-hit != 'true'
              run: |
                  cd backend
                  poetry install --no-interaction --no-root

            - name: Cache NPM packages
              uses: actions/cache@v3.4.3
              id: cache-npm
              with:
                  path: ~/frontend/node_modules
                  key: npm-${{ hashFiles('~/frontend/**/package.lock') }}
                  restore-keys: |
                      npm-${{ hashFiles('~/frontend/**/package.lock') }}

            - name: Install NPM packages
              if: steps.cache-npm.outputs.cache-hit != 'true'
              run: |
                  cd frontend/
                  npm i

            - name: Apply schema
              run: |
                    psql -h localhost -U myuser -d venome -f backups/v0.0.3/test_schema.sql
              env:
                  PGPASSWORD: mypassword


            - name: Test Backend
              working-directory: backend
              env:
                  PYTHONPATH: ../
                  DATABASE_URL: postgres://myuser:mypassword@localhost:5432/venome
                  DB_HOST: localhost
                  DB_PORT: 5432
                  DB_NAME: venome
                  DB_USER: myuser
                  DB_PASSWORD: mypassword
                  SECRET_KEY: test_secret_key
              run: |
                  poetry run pytest
                  
